### ISSUE TITLE
Ansible provisioning fails on Mac OS X 10.10.x "Yosemite"

### ISSUE THREAD

**Issue by ghost** [theclaymethod/Foundry-vagrant-mesos-kafka-cluster#3]
```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
fatal: [mesos-slave2] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [mesos-slave3] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [mesos-master1] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [mesos-slave1] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [mesos-master3] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue
fatal: [mesos-master2] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

TASK: [common | create mesosphere repo] *************************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting
```

N.B. I see many reports on the web that Yosemite has issues in recognizing modifications to /etc/hosts, and DNS resolution generally, so this may actually be an issue that needs to be reported with respect to the vagrant-hosts plugin. If you think it is, please let me know. Thanks!

**Comment by theclaymethod** [comment]
Thanks, I'll take a look. I've been afraid to upgrade to Yosemite.

**Comment by ghost** [comment]
Thanks! I don't blame you re: Yosemite. So far, I'm liking it quite a bit, but I do think this issue is related to the stuff I'm seeing about dynamically updating DNS resolution in general. If there's anything I can do to help put our finger on it, please let me know.

**Comment by rasputnik** [comment]
Sorry to chip in, but I've had no problems with the [vagrant-hostmanager plugin](https://github.com/smdahlen/vagrant-hostmanager) on Yosemite so far.

I see the stack trace you posted a lot when re-provisioning VMs (since the SSH hostkeys are changed) - does -vvvv confirm that?

**Comment by ghost** [comment]
> On Nov 23, 2014, at 3:43 PM, Dick Davies notifications@github.com wrote:
> 
> Sorry to chip in, but I've had no problems with the vagrant-hostmanager plugin https://github.com/smdahlen/vagrant-hostmanager on Yosemite so far.
> 
> I see the stack trace you posted a lot when re-provisioning VMs (since the SSH hostkeys are changed) - does -vvvv confirm that?
> 
> Nope. Happens on first “vagrant up”.

It may be worth revising the project to use hostmanager vs. hosts plugin. I’m not sure.

Actually, maybe the next thing to try is upgrading Ansible, although that’s a Hail Mary pass, because the error very definitely is that it’s trying to SSH into host(names) the (VirtualBox) host literally knows nothing about.

**Comment by rasputnik** [comment]
Ah yeah, see what you mean (just tried it out).

Not sure it's an ansible issue, even a straight

```
ssh vagrant@mesos-master1
```

hangs for me here. 
To be blunt, I dislike the way Vagrant drives Ansible so rewrote my stacks to stop Vagrant even trying. Builds are a two-step of 

```
vagrant up && ansible-playbook -i vagrant/hosts site.ml
```

but it works pretty reliably - only downside is you have to keep your _vagrant/hosts_ and _Vagrantfile_ in step when adding hosts, but it means 
1. I can switch to cloud based stacks fairly easily by dropping in a aws/hosts and aws-provision.yml
2. ansible-playbook is a lot faster to run when applying changes
3. I know which of the two to blame when crap like this happens

https://github.com/rasputnik/mesos-centos  if you're interested.

**Comment by rasputnik** [comment]
Tested vagrant-hostmanager , does seem to fix this issue on yosemite (and I've used it since mountain lion with no issues too). PR incoming.
